#################################################
# DO NOT CHANGE 
CONFIG_NAME: 'text-to-image'

DATASET_NAME: 'birds'
EMBEDDING_TYPE: 'cnn-rnn'
DATA_DIR: 'data/birds'

IMAGE_SIZE: 128
CUDA: True
WRONG_CAPTION: 9

CHECKPOINT_DIR: './checkpoint'
#################################################

GPU_ID: '0'
WORKERS: 4

BATCH_SIZE: 12

TREE:
    BASE_SIZE: 32
    BRANCH_NUM: 2


#################################################
# DO NOT CHANGE
TRAIN:
    FLAG: True
#################################################
    CNN_ENCODER: 'DAMSMencoders/bird/image_encoder200.pth' #'./evaluation/sim_models/bird/image_encoder.pth'
    RNN_ENCODER: 'DAMSMencoders/bird/text_encoder200.pth' #'./evaluation/sim_models/bird/text_encoder.pth'
    GENERATOR: '' # '../models/bird_AttnGAN2.pth'
    
    MAX_EPOCH: 600
    SNAPSHOT_INTERVAL: 50
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002

    SMOOTH:
        GAMMA1: 4.0  # 1,2,5 good 4 best  10&100bad
        GAMMA2: 5.0
        GAMMA3: 10.0  # 10good 1&100bad
        LAMBDA: 10.0
        LAMBDA1: 10.0

#################################################

CAP:
    embed_size: 256
    hidden_size: 256
    num_layers: 1
    learning_rate: 0.001
    caption_cnn_path: 'STREAM/encoder-5-3000.pkl'
    caption_rnn_path: 'STREAM/decoder-5-3000.pkl'

# DO NOT CHANGE 
TEST:
    B_EXAMPLE: False
    GENERATED_TEST_IMAGES: './evaluation/generated_images'
#################################################


RNN:
    TYPE: 'LSTM'
    
GAN:
    DF_DIM: 32
    GF_DIM: 64
    Z_DIM: 100
    CONDITION_DIM: 100
    R_NUM: 2
    
#################################################
# DO NET CHANGE 
TEXT:
    CAPTIONS_PER_IMAGE: 10
#################################################
    EMBEDDING_DIM: 256
    WORDS_NUM: 18