#################################################
# DO NOT CHANGE 
CONFIG_NAME: 'text-to-image'

DATASET_NAME: 'birds'
EMBEDDING_TYPE: 'cnn-rnn'
DATA_DIR: 'data/birds'

IMAGE_SIZE: 128
CUDA: True
WRONG_CAPTION: 9

CHECKPOINT_DIR: './checkpoint'
#################################################

GPU_ID: '0'
WORKERS: 4

BATCH_SIZE: 64

TREE:
    BASE_SIZE: 32
    BRANCH_NUM: 2


#################################################
# DO NOT CHANGE
TRAIN:
    FLAG: True
#################################################
    CNN_ENCODER: '' #'./evaluation/sim_models/bird/image_encoder.pth'
    RNN_ENCODER: '' #'./evaluation/sim_models/bird/text_encoder.pth'
    GENERATOR: ''
    
    MAX_EPOCH: 600
    SNAPSHOT_INTERVAL: 50
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002

#################################################
# DO NOT CHANGE 
TEST:
    B_EXAMPLE: False
    GENERATED_TEST_IMAGES: './evaluation/generated_images'
#################################################


RNN:
    TYPE: 'LSTM'
    
GAN:
    DF_DIM: 32
    GF_DIM: 64
    Z_DIM: 100
    CONDITION_DIM: 100
    R_NUM: 2
    
#################################################
# DO NET CHANGE 
TEXT:
    CAPTIONS_PER_IMAGE: 10
#################################################
    EMBEDDING_DIM: 256
    WORDS_NUM: 18